- name: APT | Install packages
  apt:
      state: latest
      pkg:
      - ferm
  notify: firewall-restart

- name: FERM | main config
  template: src={{ item }} dest=/etc/ferm/
  with_items:
  - ferm.conf
  notify: firewall-restart

- name: FERM | folders
  file: path=/etc/ferm/{{ item }} state=directory
  with_items:
  - input
  - output
  notify: firewall-restart

- name: FERM | configs
  template: src={{ item }} dest=/etc/ferm/input/
  with_items:
  - blacklist.conf
  notify: firewall-restart
