- name: APT | Install packages
  apt: pkg={{ item }} state=latest
  with_items:
  - ferm
  notify: firewall-restart

- name: FERM | config
  template: src={{ item }} dest=/etc/ferm/
  with_items:
  - ferm.conf
  notify: firewall-restart

- name: FERM | folders
  file: path=/etc/ferm/{{ item }} state=directory
  with_items:
  - input
  notify: firewall-restart

