- name: APT | install packages
  apt: pkg={{ item }} state=latest
  with_items:
  - backup-manager
  - ncftp

- name: UPLOAD | backup script
  template: src=dedibox_backup.sh dest=/etc/cron.daily/dedibox_backup mode=u+rx

- name: BACKUP | config
  template: src=backup-manager.conf dest=/etc/backup-manager.conf
