- name: remove certbot-auto
  file:
      path: /usr/local/certbot
      state: absent

- name: APT | snap
  apt:
    pkg:
        - snapd

# ansible-galaxy collection install community.general
- name: SNAP | certbot
  community.general.snap:
      classic: yes
      name:
          - certbot
  notify: install certbot

- meta: flush_handlers

- name: /etc/letsencrypt permissions
  file: path=/etc/letsencrypt state=directory mode=755 recurse=no

- name: /etc/letsencrypt subfolders permissions
  file: path=/etc/letsencrypt/{{item}} state=directory mode=755 recurse=yes
  with_items:
  - archive
  - live

- name: /etc/letsencrypt/nginx subfolder permissions
  file: path=/etc/letsencrypt/nginx state=directory mode=777 recurse=yes
