- name: LETSENCRYPT | work directory
  file: path={{letsencrypt_workdir}} state=directory

- import_tasks: certbot.yml

- name: crontab
  template: src=cron dest=/etc/cron.d/letsencrypt

- name: post hook
  copy:
      src: post-hook.sh
      dest: /usr/local/sbin/certbot-post-hook.sh
      mode: 0755
  
