- name: upload pip_install.sh script
  copy: src=pip_install.sh dest=/usr/local/bin/pip_install.sh mode=755

#- name: pip preinstall
#  command: /usr/local/bin/pip_install.sh preinstall
#  changed_when: False
#  tags: pip

- name: APT | ensure python is up-to-date
  apt:
    pkg:
    - python3
    - python3-dev
    - curl
    - python3-venv
    - python3-pip
    - python3-psutil
    state: latest
  tags: pip

# Bullseye
- name: Python is Python3 (bullseye specific)
  apt:
    pkg:
      - python-is-python3
  when: ansible_os_family == "Debian" and ansible_lsb.major_release|int >= 11
  tags: pip

- name: APT | Remove PIP
  apt:
    pkg: 
    - python3-pip
    - python-pip
    state: absent
  when: ansible_lsb.major_release|int >= 10
  tags: pip


- name: pip install
  command: /usr/local/bin/pip_install.sh install
  changed_when: False
  when: ansible_lsb.major_release|int >= 10
  tags: pip

- name: install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 -
  tags: pip

- name: update poetry
  command: /root/.local/bin/poetry self update
  tags: pip
