- name: upload pip_install.sh script
  copy: src=pip_install.sh dest=/usr/local/bin/pip_install.sh mode=755

#- name: pip preinstall
#  command: /usr/local/bin/pip_install.sh preinstall
#  changed_when: False
#  tags: pip

- name: APT | ensure python is up-to-date
  apt:
    pkg:
    - python3
    - python3-dev
    - curl
    state: latest

- name: APT | Remove PIP
  apt:
    pkg: ['python3-pip', 'python-pip']
    state: absent
  when: ansible_lsb.major_release|int >= 7
  tags: pip


- name: pip install
  command: /usr/local/bin/pip_install.sh install
  changed_when: False
  tags: pip

- include_tasks: pip_version.yml
  tags: pip

