- name: apt https
  apt: pkg=apt-transport-https state=present

- name: apt key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: apt repository
  apt_repository: repo='deb https://packagecloud.io/grafana/stable/debian/ wheezy main' state=present 

- name: apt grafana
  apt: pkg=grafana state=latest

- name: grafana.ini
  template: src=grafana.ini dest=/etc/grafana/grafana.ini
  notify: grafana restart

- name: grafana plugins
  command: /usr/sbin/grafana-cli plugins install {{ item }}
  with_items: grafana_plugins
  when: grafana_plugins is defined
  notify: grafana restart
