- name: Download DEB
  get_url: dest=/tmp/influxdb-{{influxdb_version}}.deb url=https://dl.influxdata.com/influxdb/releases/influxdb_{{influxdb_version}}_amd64.deb
  register: influxdb_download_deb

- name: Install InfluxDB deb
  apt: deb=/tmp/influxdb-{{influxdb_version}}.deb
  when: influxdb_download_deb|changed
  notify: restart influxdb

#- name: collectd types.db
#  synchronize:
#    src: /usr/share/collectd/types.db
#    dest: /etc/influxdb/collectd_types.db
#  delegate_to: "{{collectd_main}}"
#  when: collectd_main is defined

- name: configuration
  template: src=influxdb.conf dest=/etc/influxdb/influxdb.conf
  notify: restart influxdb

- name: data directory
  file: path={{ influxdb_directory }} state=directory owner=influxdb group=influxdb

- meta: flush_handlers
 
- name: ensure influxdb is started
  service: name=influxdb state=started
